/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on May 25, 2010, 2:40:29 PM
 */
package edu.berkeley.lhs.digitarium;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.*;

import nightshade.RealTalker;
import nightshade.StelTalker;

public class MainFrame extends javax.swing.JFrame implements WindowListener {

	private static final long serialVersionUID = 613723562382702988L;

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel1 = new edu.berkeley.lhs.digitarium.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 624, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(final String args[]) {
		try {
			OutputStream os;
			if (args.length > 0) {
				PipedInputStream is = new PipedInputStream();
				os = new PipedOutputStream(is);
				Runnable st;
				if (args.length > 1) {
					st = new RealTalker(args[0], is);
				} else {
					st = new StelTalker(args[0], is);
				}
				new Thread(st).start();
			} else {
				os = System.out;
			}
			MainFrame mf = new MainFrame();
			mf.mainPanel1.setStream(os);
			mf.setVisible(true);
		} catch (IOException ioe) {
			ioe.printStackTrace();
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.berkeley.lhs.digitarium.MainPanel mainPanel1;
    // End of variables declaration//GEN-END:variables

	public void windowOpened(WindowEvent e) {
	}

	public void windowClosing(WindowEvent e) {
		mainPanel1.destroy();
	}

	public void windowClosed(WindowEvent e) {
		mainPanel1.destroy();
	}

	public void windowIconified(WindowEvent e) {
	}

	public void windowDeiconified(WindowEvent e) {
	}

	public void windowActivated(WindowEvent e) {
	}

	public void windowDeactivated(WindowEvent e) {
	}
}
