/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPanel.java
 *
 * Created on May 28, 2010, 2:27:42 PM
 */
package edu.berkeley.lhs.digitarium;

import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import java.io.*;

public class MainPanel extends javax.swing.JPanel implements CommandListener,
		ChangeListener {

	private static final long serialVersionUID = 2775393934961748596L;
	public static final int WELCOME_SCREEN = 0;
	public static final int CONSTELLATIONS = 1;
	public static final int MOON_PHASES = 3;
	public PrintStream writeStream;
	private int currentState;

	public void setStream(OutputStream os) {
		writeStream = new PrintStream(os);
	}

	/** Creates new form MainPanel */
	public MainPanel() {
		initComponents();
		dateChooser1.setCommandListener(this);
		constellationChooser1.setCommandListener(this);
		moonPanel1.setCommandListener(this);
		jTabbedPane1.addChangeListener(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new edu.berkeley.lhs.digitarium.DateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        constellationChooser1 = new edu.berkeley.lhs.digitarium.ConstellationChooser();
        jPanel3 = new javax.swing.JPanel();
        moonPanel1 = new edu.berkeley.lhs.digitarium.MoonPanel();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lawrence Hall of Science, Plan-My-tarium");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Welcome", jPanel2);
        jTabbedPane1.addTab("Constellations", constellationChooser1);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 578, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 492, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);
        jTabbedPane1.addTab("Moon Phases", moonPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, dateChooser1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dateChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.berkeley.lhs.digitarium.ConstellationChooser constellationChooser1;
    private edu.berkeley.lhs.digitarium.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private edu.berkeley.lhs.digitarium.MoonPanel moonPanel1;
    // End of variables declaration//GEN-END:variables

	public void commandOccured(String command) {
		writeStream.println(command);
	}

	public void destroy() {
		writeStream.println("end");
	}

	public void stateChanged(ChangeEvent e) {
		switch (currentState) {
		case CONSTELLATIONS:
			constellationChooser1.exitMode();
			break;
		case MOON_PHASES:
			moonPanel1.exitMode();
			break;
		}
		dateChooser1.resetTime();
		currentState = jTabbedPane1.getSelectedIndex();
		switch (currentState) {
		case CONSTELLATIONS:
			constellationChooser1.enterMode();
			break;
		case MOON_PHASES:
			moonPanel1.enterMode();
			break;
		}
	}
}
