/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoonPanel.java
 *
 * Created on Jun 2, 2010, 3:12:15 PM
 */
package edu.berkeley.lhs.digitarium;

public class MoonPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -4544004687921560455L;
	private CommandListener commandListener;

	/** Creates new form MoonPanel */
	public MoonPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		moonIcon1 = new edu.berkeley.lhs.digitarium.MoonIcon();

		jButton1.setLabel("<<");

		jButton2.setLabel(">>");

		org.jdesktop.layout.GroupLayout moonIcon1Layout = new org.jdesktop.layout.GroupLayout(
				moonIcon1);
		moonIcon1.setLayout(moonIcon1Layout);
		moonIcon1Layout.setHorizontalGroup(moonIcon1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 42,
				Short.MAX_VALUE));
		moonIcon1Layout.setVerticalGroup(moonIcon1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 30,
				Short.MAX_VALUE));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jButton1)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												moonIcon1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jButton2).addContainerGap(90,
												Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(
						layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING).add(
								moonIcon1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).add(jButton2,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								30, Short.MAX_VALUE).add(jButton1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								30, Short.MAX_VALUE)).addContainerGap(162,
						Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private edu.berkeley.lhs.digitarium.MoonIcon moonIcon1;

	// End of variables declaration//GEN-END:variables

	public void enterMode() {
		fireCommand("flag moon_scaled on");
	}

	public void exitMode() {
		fireCommand("flag moon_scaled off");
	}

	public void setCommandListener(CommandListener listener) {
		commandListener = listener;
	}

	private void fireCommand(String command) {
		commandListener.commandOccured(command);
	}
}
